service: web-www-officemsoft-com
image: jackwillis/www.officemsoft.com

servers:
  - 1337.attac.us

proxy:
  ssl: true
  host:
    - www.officemsoft.com
    - officemsoft.com

ssh:
  user: george

builder:
  arch: amd64

registry:
  server: ghcr.io
  username: jackwillis
  password: <%= ENV['KAMAL_REGISTRY_PASSWORD'] %>
